# This action continuously checks all pushes and Pull requests
# for validity, integrity and bugs in datafiles.
# For details, visit https://github.com/BSData/check-datafiles
name: Generic Datafile validations
on:
  push:
    branches:
      - main
  pull_request_target:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out BSCopy
      uses: actions/checkout@v4
      with:
        repository: 'nstephenh/bscopy'
    - name: Checking out game system
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: ${{ github.workspace }}/${{ github.repository }}/
    - name: Setting up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Get game system name from repo name
      run: |
        SYSTEM_NAME=$(basename "${{ github.repository }}")
        echo "System Name: $SYSTEM_NAME"
        echo "SYSTEM_NAME=$SYSTEM_NAME" >> $GITHUB_ENV
      env:
        DEFAULT_DATA_DIRECTORY: ${{ github.workspace }}/${{ github.repository }}/../
    - name: set pythonpath
      run: |
        echo "PYTHONPATH=." >> $GITHUB_ENV
    - name: Run basic validity
      id: validity
      run: |      
        python3 system/tests/basic_system_checks.py
      env:
        DEFAULT_DATA_DIRECTORY: ${{ github.workspace }}/${{ github.repository }}/../


#    - uses: BSData/check-datafiles@v1
#      id: check

